### ISSUE TITLE
“JC303.component” can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by lgustavomartins** [midilab/jc303#10]
Getting this error in Logic Pro 10.8.1 and MacOS 14.3.1, runing on a MBP16M3Max:  

`“JC303.component” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.`

```
validating Audio Unit JC303 by midilab:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'J303' - 'Mlab'
--------------------------------------------------
Manufacturer String: midilab
AudioUnit Name: JC303
Component Version: 0.10.1 (0xA01)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
```

**Comment by midilab** [comment]
The plugin is not signed, i dont have a apple developer account to sign either. 

What you can do is to de-quarantine the plugin. You can read more about over the internet on how to de-quarantine a app/plugin based on your mac os version.

Apple asks developers $100 dollars a year just to let you sign the app just to say "it is secure now", and since its a opensource project and you can read the code or even compile it your self i see no means on paying then each year $100 just to sign it.

I will update the documentation asap with notes about sign and de-quarantine since this could be a common question for mac users.

**Comment by lgustavomartins** [comment]
> The plugin is not signed, i dont have a apple developer account to sign either.
> 
> What you can do is to de-quarantine the plugin. You can read more about over the internet on how to de-quarantine a app/plugin based on your mac os version.
> 
> Apple asks developers $100 dollars a year just to let you sign the app just to say "it is secure now", and since its a opensource project and you can read the code or even compile it your self i see no means on paying then each year $100 just to sign it.
> 
> I will update the documentation asap with notes about sign and de-quarantine since this could be a common question for mac users.

Thank you for the promptly reply and suggestion! I've managed to easily de-quarantine the JC303 plugin following the instructions found in this webpage: [](https://syntheway.com/fix-au-vst-vst3-macos.htm) 

In Summary, you just need to type this at a terminal window:

`sudo xattr -rd com.apple.quarantine /Library/Audio/Plug-Ins/Components/JC303.component`

Thank you for the excellent plug-in and all the hard work!!

**Comment by midilab** [comment]
great! 

thanks for the information! i will update asap the readme on how to de-quarantine.
