### ISSUE TITLE
this plugin should automatically bypass if it detects an audio sample

### ISSUE THREAD

**Issue by RustoMCSpit** [midilab/jc303#14]
as it only works with midi, it should not effect audio. there should also be a warning displayed

**Comment by midilab** [comment]
is there any audio leaking happening on your audio input? what DAW and OS you're using? 

Strange since JUCE setup for only MIDI should total disable any audio input.

**Comment by RustoMCSpit** [comment]
yeah, bitwig 5.8

**Comment by midilab** [comment]
After look at it, i see no signs of audio leakage, i couldn't reproduce the scenario you point it to me.

Im guessing there is some configuration on your setup allowing bitwig to pass audio thru on jc303 channel for some reason.

Since its Juce based plugin and there is no audio input declared on plugin compilation is unprobable that the plugin is passing thru audio since there is no code inside handle those audio bytes. 

If this is happen(not only on your bitwig setup) we have a Juce bug, in that case you should report this behaviour to Juce project guys instead.

**Comment by RustoMCSpit** [comment]
forget this
